const api = {
    apiModule: '/ApiModule',
    getMyModule: '/ApiModule/GetByModule',
    incomeDetail: '/IncomeDetail',
    liquidityDetail: 'LiquidityDetail',
    JWTToken: '/Login/JWTToken',
    refreshToken: '/Login/RefreshToken',
    module: '/Module',
    power: '/Power',
    secure: '/Secure',
    secureUser: '/SecureUser',
    getAnswer: '/SecureUser/GetAnswer',
    spendingDetail: '/SpendingDetail',
    storageDetail: '/StorageDetail',
    tallyType: '/TallyType',
    getParentType: '/TallyType/getParentType',
    getTypeByTypeId: '/TallyType/getTypeByTypeId',
    user: '/User',
    modifyPassword: '/User/ModifyPassword',   
};
export default api;